pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                echo "Creating venv and Installing dependencies..."
                // Create a virtual environment named 'venv' and install requirements inside it
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    python3 -m pip install --upgrade pip
                    python3 -m pip install -r requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps {
                echo "Running tests..."    
                // Activate the venv before running pytest
                sh '''
                    . venv/bin/activate
                    python3 -m pytest
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building the application..."
                // Activate the venv before running the app
                sh '''
                    . venv/bin/activate
                    python3 app.py
                '''
            }
        }
    }
}